name: "Hello Action World 2"
description: "Une action simple pour GitHub"
author: "Jensone"
inputs:
  name:
    description: "Nom de l'utilisateur"
    required: true
    default: "World"
runs:
  using: "node20"
  main: "index.js"

branding:
  icon: "message-square"
  color: "blue"
